name: Test
on: [ push ]
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-runners
    #что делаем
    steps:
      #выкачиваем репозиторий
      - uses: actions/checkout@v3
        #настриваем java
      - uses: actions/setup-java@v3
      - uses: Xotabu4/selenoid-github-action@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          #запускаем тестыssss
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:5678/wd/hub