name: Test

on: [push]
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:
      #выкачиваем репозиторий
      - uses: actions/checkout@v3
        #настриваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      -  uses: Xotabu4/selenoid-github-action@v2
          #запускаем тестыssss
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub